name: Deploy Micro

on:
  push:
    branches: [main]

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-24.04
    environment: production
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
      - uses: microdotdo/micro-action@0efeeb544fcb375372adc4211fd4e7227e6ed275 # v1.4.1
